version: '3'
services:
  myarch:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.arch
      args:
        GIT_USER: ${GIT_USER}
        GIT_PASS: ${GIT_PASS}
    volumes:
      - ~/workspace:/workspace
    ports:
      - '2222:22'
